export type TaskType =
  | 'DISCOVER_TOKENS_API'
  | 'SYNC_VENUE_MARKETS'
  | 'RESOLVE_TOKEN_VENUES'
  | 'INGEST_OHLCV_API'
  | 'INGEST_OHLCV_WS'
  | 'REVERIFY_API_ONLY';

export const HIGH_PRIORITY_TYPES: TaskType[] = ['INGEST_OHLCV_API', 'INGEST_OHLCV_WS'];
